[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/rose-pine-moon.toml"]
# import = ["~/.config/alacritty/themes/flexoki-dark.toml"]

[terminal]
shell = "/opt/homebrew/bin/fish"

[window]
option_as_alt = "Both"

[font]
normal.family = "JetBrainsMono Nerd Font"
size = 13

[cursor]
# style.blinking = "On"
style.shape = "Block"


[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u001bOH"

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u001bOF"
